server:
  port: 8080 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  add-proxy-headers: true
  routes:
    farmers:
      path: /api/**
      stripPrefix: false
    customers: /api/customers/**
    orders: /api/orders/**